#!/bin/bash

# Set the time zone
ln -sf /usr/share/zoneinfo/Europe/Moscow /etc/localtime
hwclock --systohc

# Localization
sed -i 's/^#en_US.UTF-8/en_US.UTF-8/' /etc/locale.gen
sed -i 's/^#ru_RU.UTF-8/ru_RU.UTF-8/' /etc/locale.gen
locale-gen

echo "LANG=ru_RU.UTF-8" >> /etc/locale.conf
echo "KEYMAP=ru" >> /etc/vconsole.conf
echo "FONT=cyr-sun16" >> /etc/vconsole.conf

# Network configuration
echo "archlinux" >> /etc/hostname

echo "127.0.0.1    localhost" >> /etc/hosts
echo "::1          localhost" >> /etc/hosts
echo "127.0.0.1    archlinux.localdomain  archlinux" >> /etc/hosts

systemctl enable NetworkManager

# Add multilib repo
line=`grep -n "#\[multilib\]" /etc/pacman.conf | cut -d':' -f1`
sed -i -e "${line}s/^#//" /etc/pacman.conf
line=$((line+1))
sed -i -e "${line}s/^#//" /etc/pacman.conf

# Passwords and create user
echo; echo
echo "####################"
echo "Password for root"
echo "####################"
passwd

echo; echo
echo "####################"
echo "Add user"
echo "####################"
read  -p"Username >" username
useradd -m -G wheel -s /bin/bash $username
passwd $username

# Copy scripts
chmod -R 755 /home/$username
cp -r /root/archlinux_installer /home/$username
chown -R $username:$username /home/$username/archlinux_installer

# Add sudo
sed -i 's/# %wheel ALL=(ALL) ALL/%wheel ALL=(ALL) ALL/' /etc/sudoers

# Install GRUB
grub=`pacman -Qe grub 2>/dev/null | grep -o "^grub"`
efibootmgr=`pacman -Qe efibootmgr 2>/dev/null | grep -o "^efibootmgr"`

if [[ $grub == "grub" ]]; then
    if [[ $efibootmgr == "efibootmgr" ]]; then
        grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=GRUB
        grub-mkconfig -o /boot/grub/grub.cfg
        echo "####################"
        echo "GRUB for EFI install"
        echo "####################"
    else
        grub-install --target=i386-pc /dev/sda
        grub-mkconfig -o /boot/grub/grub.cfg
        echo "####################"
        echo "GRUB for MBR install"
        echo "####################"
    fi
else
    echo "####################"
    echo "GRUB not install"
    echo "####################"
fi

# Exit
echo "####################"
echo "Please do this:"
echo ">exit"
echo "####################"

