#!/usr/bin/env bash

#
# creating a working link system (for Koljasha disk's system)
# required:
#
# sudo mkdir /run/mount/storage
# sudo chown koljasha:koljasha /run/mount/storage
#
# sudo vim /etc/fstab:
# /dev/sda4 LABAL=Storage
# UUID=c6ab23b5-1b6d-4c3f-8488-6efee0144e54	/run/mount/storage/	ext4	rw,relatime	0 2
#

# home dirs
rm -rf ~/Downloads
ln -s /run/mount/storage/home/Downloads ~/Downloads
rm -rf ~/Share
ln -s /run/mount/storage/home/Share ~/Share
rm -rf ~/Video
ln -s /run/mount/storage/home/Video ~/Video
rm -rf ~/Work
ln -s /run/mount/storage/home/Work ~/Work
rm -rf ~/tmp
ln -s /run/mount/storage/home/tmp ~/tmp

# gitconfig
rm -rf ~/.gitconfig
ln -s /run/mount/storage/local/settings/gitconfig ~/.gitconfig

# key dirs
rm -rf ~/.gnupg
ln -s /run/mount/storage/local/settings/gnupg ~/.gnupg
rm -rf ~/.password-store
ln -s /run/mount/storage/local/settings/password-store ~/.password-store
rm -rf ~/.ssh
ln -s /run/mount/storage/local/settings/ssh ~/.ssh

# firefox dirs
rm -rf ~/.mozilla/firefox
mkdir -p ~/.mozilla
ln -s /run/mount/storage/local/settings/firefox ~/.mozilla/firefox

# gnome-boxes dirs
rm -rf ~/.local/share/gnome-boxes
ln -s /run/mount/storage/local/gnome-boxes ~/.local/share/gnome-boxes

#
# ~/.config
#

# Kvantum
rm -rf ~/.config/Kvantum
ln -s /run/mount/storage/local/config/Kvantum ~/.config/Kvantum

# alacritty
rm -rf ~/.config/alacritty
ln -s /run/mount/storage/local/config/alacritty ~/.config/alacritty

# dunst
rm -rf ~/.config/dunst
ln -s /run/mount/storage/local/config/dunst ~/.config/dunst

# fish
rm -rf ~/.config/fish
ln -s /run/mount/storage/local/config/fish ~/.config/fish

# gsimplecal
rm -rf ~/.config/gsimplecal
ln -s /run/mount/storage/local/config/gsimplecal ~/.config/gsimplecal

# gtk-3.0
rm -rf ~/.config/gtk-3.0
ln -s /run/mount/storage/local/config/gtk-3.0 ~/.config/gtk-3.0

# gtk-4.0
rm -rf ~/.config/gtk-4.0
ln -s /run/mount/storage/local/config/gtk-4.0 ~/.config/gtk-4.0

# htop
rm -rf ~/.config/htop
ln -s /run/mount/storage/local/config/htop ~/.config/htop

# i3
rm -rf ~/.config/i3
ln -s /run/mount/storage/local/config/i3 ~/.config/i3

# jgmenu
rm -rf ~/.config/jgmenu
ln -s /run/mount/storage/local/config/jgmenu ~/.config/jgmenu

# nvim
rm -rf ~/.config/nvim
ln -s /run/mount/storage/local/config/nvim ~/.config/nvim

# openbox
rm -rf ~/.config/openbox
ln -s /run/mount/storage/local/config/openbox ~/.config/openbox

# picom
rm -rf ~/.config/picom
ln -s /run/mount/storage/local/config/picom ~/.config/picom

# polybar
rm -rf ~/.config/polybar
ln -s /run/mount/storage/local/config/polybar ~/.config/polybar

# qt5ct
rm -rf ~/.config/qt5ct
ln -s /run/mount/storage/local/config/qt5ct ~/.config/qt5ct

# qt6ct
rm -rf ~/.config/qt6ct
ln -s /run/mount/storage/local/config/qt6ct ~/.config/qt6ct

# qtile
rm -rf ~/.config/qtile
ln -s /run/mount/storage/local/config/qtile ~/.config/qtile

# qutebrowser
rm -rf ~/.config/qutebrowser
ln -s /run/mount/storage/local/config/qutebrowser ~/.config/qutebrowser

# ranger
rm -rf ~/.config/ranger
ln -s /run/mount/storage/local/config/ranger ~/.config/ranger

# remmina
rm -rf ~/.config/remmina ~/.local/share/remmina
ln -s /run/mount/storage/local/config/remmina ~/.config/remmina
ln -s /run/mount/storage/local/settings/remmina_local ~/.local/share/remmina

# rofi
rm -rf ~/.config/rofi
ln -s /run/mount/storage/local/config/rofi ~/.config/rofi

# scripts
rm -rf ~/.config/scripts
ln -s /run/mount/storage/local/config/scripts ~/.config/scripts

# swappy
rm -rf ~/.config/swappy
ln -s /run/mount/storage/local/config/swappy ~/.config/swappy

# terminator
rm -rf ~/.config/terminator
ln -s /run/mount/storage/local/config/terminator ~/.config/terminator

# tmux
rm -rf ~/.config/tmux
ln -s /run/mount/storage/local/config/tmux ~/.config/tmux

# vim
rm -rf ~/.config/vim
ln -s /run/mount/storage/local/config/vim ~/.config/vim
rm -rf ~/.vimrc ~/.gvimrc
ln -s ~/.config/vim/vimrc ~/.vimrc
ln -s ~/.config/vim/gvimrc ~/.gvimrc
rm -rf ~/.vim
ln -s /run/mount/storage/local/settings/vim ~/.vim

# xbindkeys
rm -rf ~/.config/xbindkeys
ln -s /run/mount/storage/local/config/xbindkeys ~/.config/xbindkeys

