#!/usr/bin/env bash

#
# creating a working link system (for Koljasha disk's system)
# required:
#
# sudo mkdir /run/mount/storage
# sudo chown koljasha:koljasha /run/mount/storage
#
# sudo vim /etc/fstab:
# /dev/sda4 LABAL=Storage
# UUID=c6ab23b5-1b6d-4c3f-8488-6efee0144e54	/run/mount/storage/	ext4	rw,relatime	0 2
#

# home dirs
rm -rf ~/Downloads
ln -s /run/mount/storage/home/Downloads ~/Downloads
rm -rf ~/Video
ln -s /run/mount/storage/home/Video ~/Video
rm -rf ~/Work
ln -s /run/mount/storage/home/Work ~/Work
rm -rf ~/tmp
ln -s /run/mount/storage/home/tmp ~/tmp

# key dirs
rm -rf ~/.gnupg
ln -s /run/mount/storage/local/settings/gnupg ~/.gnupg
rm -rf ~/.password-store
ln -s /run/mount/storage/local/settings/password-store ~/.password-store
rm -rf ~/.ssh
ln -s /run/mount/storage/local/settings/ssh ~/.ssh

# vim dirs|files
rm -rf ~/.vim ~/.vimrc ~/.gvimrc
ln -s /run/mount/storage/local/settings/vim ~/.vim
ln -s ~/.vim/vimrc ~/.vimrc
ln -s ~/.vim/gvimrc ~/.gvimrc

# firefox dirs
rm -rf ~/.mozilla/firefox
mkdir -p ~/.mozilla
ln -s /run/mount/storage/local/settings/firefox ~/.mozilla/firefox

# gnome-boxes dirs
rm -rf ~/.local/share/gnome-boxes
ln -s /run/mount/storage/local/gnome-boxes ~/.local/share/gnome-boxes

#
# ~/.config
#

# Kvantum
rm -rf ~/.config/Kvantum
ln -s /run/mount/storage/local/config/Kvantum ~/.config/Kvantum

# alacritty
rm -rf ~/.config/alacritty
ln -s /run/mount/storage/local/config/alacritty ~/.config/alacritty

# dunst
rm -rf ~/.config/dunst
ln -s /run/mount/storage/local/config/dunst ~/.config/dunst

# fish
rm -rf ~/.config/fish
ln -s /run/mount/storage/local/config/fish ~/.config/fish

# gsimplecal
rm -rf ~/.config/gsimplecal
ln -s /run/mount/storage/local/config/gsimplecal ~/.config/gsimplecal

# remmina
rm -rf ~/.config/remmina ~/.local/share/remmina
ln -s /run/mount/storage/local/config/remmina ~/.config/remmina
ln -s /run/mount/storage/local/settings/remmina_local ~/.local/share/remmina

# rofi
rm -rf ~/.config/rofi
ln -s /run/mount/storage/local/config/rofi ~/.config/rofi

# scripts
rm -rf ~/.config/scripts
ln -s /run/mount/storage/local/config/scripts ~/.config/scripts

# terminator
rm -rf ~/.config/terminator
ln -s /run/mount/storage/local/config/terminator ~/.config/terminator

# tmux
rm -rf ~/.config/tmux
ln -s /run/mount/storage/local/config/tmux ~/.config/tmux

# xbindkeys
rm -rf ~/.config/xbindkeys
ln -s /run/mount/storage/local/config/xbindkeys ~/.config/xbindkeys

