#!/bin/bash

echo "####################"
echo "Install packages"
echo "####################"
echo; echo

# Select video drivers
echo "####################"
echo "What video drivers install?"
echo "1) xf86-video-intel      -> for Intel"
echo "2) xf86-video-nouveau    -> for nVidea"
echo "other) xf86-video-fbdev  -> other driver"
echo "####################"

read -n1 -p">" drivers; echo
if [[ $drivers == "1" ]]; then
    drivers="xf86-video-intel"
elif [[ $drivers == "2" ]]; then
    drivers="xf86-video-nouveau"
else
    drivers="xf86-video-fbdev"
fi

# Packages
packages="
$drivers linux-headers
dosfstools mtools man-db man-pages reflector xdg-user-dirs bash-completion ntfs-3g gvfs
atool p7zip unrar unzip zip
git htop lm_sensors lesspipe numlockx wget curl cmake ctags neofetch highlight
vim fish tmux ranger
ttf-droid ttf-dejavu ttf-font-awesome ttf-nerd-fonts-symbols
arc-gtk-theme arc-icon-theme xcursor-vanilla-dmz gnome-backgrounds
xorg lightdm lightdm-gtk-greeter lightdm-gtk-greeter-settings accountsservice
feh picom
openbox i3 obconf lxappearance polkit-gnome
terminator gnome-terminal pcmanfm-gtk3
menumaker zenity dmenu rofi jgmenu plank xfce4-appfinder
gsimplecal gnome-calendar gnome-screenshot gnome-calculator file-roller
viewnior evince
"
packages_aur="
xkb-switch
arc-dark-osx-openbox-theme-git
mintstick sublime-text-3
"

# ----------
# pulseaudio pulseaudio-alsa
# network-manager-applet openvpn networkmanager-openvpn
# openssh samba x11vnc
# vlc firefox remmina transmission-gtk
# -----------
# https://aur.archlinux.org/polybar.git
# -----------

# Install packages from repo
sudo pacman -Sy
sudo pacman -S --needed --noconfirm $packages

# build yay
git clone https://aur.archlinux.org/yay.git
cd yay && makepkg -sirc --noconfirm
cd .. && rm -rf yay

yay -S --noconfirm $packages_aur

###############

username=`whoami`

###############

# Copy configs
cp files/bashrc ~/.bashrc
cp files/vimrc ~/.vimrc
cp files/tmux.conf ~/.tmux.conf
cp files/face ~/.face

cp -r config/ ~/.config

sudo cp files/lightdm-gtk-greeter.conf /etc/lightdm/lightdm-gtk-greeter.conf

###############

# Packages settings

# install Vim-plug
curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
# install vim spell RU UTF-8
curl -fLo ~/.vim/spell/ru.utf-8.sug --create-dirs http://ftp.vim.org/vim/runtime/spell/ru.utf-8.sug
curl -fLo ~/.vim/spell/ru.utf-8.spl --create-dirs http://ftp.vim.org/vim/runtime/spell/ru.utf-8.spl
# install vim pluggins
vim -c PlugInstall
# enable vim colorscheme
sed -i 's/desert/PaperColor/' ~/.vimrc

# install oh-my-fish
git clone https://github.com/oh-my-fish/oh-my-fish
oh-my-fish/bin/install --noninteractive --offline
# install theme for fish
fish -c 'omf install agnoster'
# clean oh-my-fish
rm -rf ~/archlinux_installer/oh-my-fish

# ranger icons
git clone https://github.com/cdump/ranger-devicons2 ~/.config/ranger/plugins/devicons2

# picom settings
mkdir ~/.config/picom
cp /etc/xdg/picom.conf ~/.config/picom/picom.conf
##### for Virtual Box ### Check for real PC #####
sed -i 's/^# vsync = false/vsync = false/' ~/.config/picom/picom.conf
sed -i 's/^vsync = true/# vsync = true/' ~/.config/picom/picom.conf

# gnome-screenshot settings
gsettings set org.gnome.gnome-screenshot auto-save-directory "file:///home/$username/Загрузки/"

###############

# Enable services
sudo systemctl enable lightdm

###############

# end update settings

# fish is main shell
sudo chsh -s /usr/bin/fish $username
# update fish
fish -c 'fish_update_completions'

# menumaker for Openbox
# mmaker -f -t GNOME-terminal OpenBox3

###############

echo; echo
echo "####################"
echo "Please do this:"
echo ">reboot"
echo "####################"

