#!/bin/bash

echo "####################"
echo "Install packages"
echo "####################"
echo; echo

# Select video drivers
echo "####################"
echo "What video drivers install?"
echo "1) xf86-video-intel    -> for Intel"
echo "2) xf86-video-nouveau  -> for nVidea"
echo "3) xf86-video-fbdev    -> for virtual"
echo "other key              -> no driver"
echo "####################"

read -n1 -p">" drivers; echo
if [[ $drivers == "1" ]]; then
    drivers="xf86-video-intel"
elif [[ $drivers == "2" ]]; then
    drivers="xf86-video-nouveau"
elif [[ $drivers == "3" ]]; then
    drivers="xf86-video-fbdev"
else
    drivers=""
fi

# Packages
packages="
$drivers linux-headers
dosfstools mtools man-db man-pages reflector xdg-user-dirs bash-completion
atool p7zip unrar unzip zip
git htop lm_sensors lesspipe numlockx wget curl cmake neofetch highlight ctags
vim fish
"

# ----------
# fish tmux ranger
# noto-fonts ttf-droid ttf-dejavu ttf-font-awesome ttf-nerd-fonts-symbols
# arc-gtk-theme arc-icon-theme xcursor-vanilla-dmz gnome-backgrounds
# xorg lightdm lightdm-gtk-greeter lightdm-gtk-greeter-settings accountsservice
# openbox i3 obconf lxappearance
# pulseaudio pulseaudio-alsa
# polkit-gnome network-manager-applet networkmanager-openvpn
# feh picom
# menumaker zenity dmenu rofi jgmenu plank xfce4-appfinder
# terminator gnome-terminal 
# gsimplecal gnome-calendar gnome-screenshot gnome-calculator file-roller
# sublime-text-3 pcmanfm-gtk3 viewnior evince vlc firefox remmina
# openssh samba openvpn x11vnc
# -----------
# https://aur.archlinux.org/yay.git
# 
# https://aur.archlinux.org/polybar.git
# https://aur.archlinux.org/xkb-switch.git
# 
# https://aur.archlinux.org/arc-dark-osx-openbox-theme-git.git
# https://aur.archlinux.org/mint-x-icons.git
# -----------


# Install packages from repo
sudo pacman -Sy
sudo pacman -S --needed $packages

###############

# Enable services
# sudo systemctl enable lightdm

###############

# Copy configs
cp files/bashrc ~/.bashrc
cp files/vimrc ~/.vimrc
cp -r config/* ~/.config

###############

# Packages settings
username=`whoami`

# install Vim-plug
curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
# install vim spell RU UTF-8
curl -fLo ~/.vim/spell/ru.utf-8.sug --create-dirs http://ftp.vim.org/vim/runtime/spell/ru.utf-8.sug
curl -fLo ~/.vim/spell/ru.utf-8.spl --create-dirs http://ftp.vim.org/vim/runtime/spell/ru.utf-8.spl
# install vim pluggins
vim -c PlugInstall
# enable vim colorscheme
sed -n 's/desert/PaperColor/p' files/vimrc

# install oh-my-fish
git clone https://github.com/oh-my-fish/oh-my-fish
oh-my-fish/bin/install --noninteractive --offline
# install theme for fosh
fish -c 'omf install agnoster'
# clean oh-my-fish
rm -rf ~/archlinux_installer/oh-my-fish

###############

# end update settings

# fish is main shell
# sudo chsh -s /usr/bin/fish $username
# update fish
# fish -c 'fish_update_completions'

###############

echo "####################"
echo "Please do this:"
echo ">reboot"
echo "####################"

