#!/usr/bin/env bash

# Создание swapfile; запись в fstab

if [[ $(whoami) != 'root' ]]; then
    echo 'Need run form sudo'
    exit 2
fi

# Создание
# dd if=/dev/zero of=/swapfile bs=1M count=4k status=progress
# или
# fallocate -l 4G /swapfile

# chmod 0600 /swapfile
# mkswap -U clear /swapfile

mkswap -U clear --size 4G --file /swapfile
swapon /swapfile

# Включение
echo '# swapfile' >> /etc/fstab
echo '/swapfile   none    swap    defaults    0 0' >> /etc/fstab
echo '' >> /etc/fstab

cat /etc/fstab

