" ----------------------------------------
" gvimrc by Koljasha
" ----------------------------------------

" ----------------------------------------
" eVim - перейти в normal mode: ctrl-l
" ----------------------------------------

" настройка цветовой схемы
colorscheme PaperColor
" размер окна
set lines=45 columns=150

" убрать gui
set guioptions=

" шрифт
set guifont=Monospace,10

" убрать Toolbar
" set guioptions-=T
" убрать Menu
" set guioptions-=m

