" ----------------------------------------
" vimrc by Koljasha
" ----------------------------------------

" Базовые настройки
source ~/.config/vim/settings.vim

" Привязки клавиш
source ~/.config/vim/mappings.vim

" Терминал и Проводник
source ~/.config/vim/explorers.vim

" ----------------------------------------
" ----------------------------------------
" Плагины
" ----------------------------------------

" Vim-plug - менеджер плагинов
" ---------------
" https://github.com/junegunn/vim-plug
" Reload .vimrc and :PlugInstall to install plugins
" --------------

" Initialize plugin system
call plug#begin()

" ----------------------------------------

" Основные плагины
source ~/.config/vim/pluggins.vim

" Ide плагины (Emmet, Black)
" source ~/.config/vim/ide.vim

" Lsp плагины Vim
" source ~/.config/vim/lsp.vim

" ----------------------------------------

" Initialize plugin system
call plug#end()

" ----------------------------------------
" ----------------------------------------

" Цветовая схема (через плагин)
source ~/.config/vim/colors.vim

" ----------------------------------------
" ----------------------------------------

