#!/bin/bash

# disable display
off (){
    # M310 - name of mouse
    mouse_id=`xinput list | grep M310 | awk '{print $5}' | cut -d'=' -f2`
    xinput disable $mouse_id
    xset dpms force off
}

# enable mouse after disable display
on (){
    # M310 - name of mouse
    mouse_id=`xinput list | grep M310 | awk '{print $5}' | cut -d'=' -f2`
    xinput enable $mouse_id
    xset -dpms
}

# set brightness
sbr (){
    # eDP-1 - display output
    xrandr --output eDP-1 --brightness $1
}

# disable brightness
dbr (){
    # eDP-1 - display output
    default_brightness=`xrandr --verbose | grep -i brightness | cut -d':' -f2 | cut -c2-`
    xrandr --output eDP-1 --brightness 0
    read -n1
    xrandr --output eDP-1 --brightness $default_brightness
}

if [[ $1 == 'off' ]]; then
    off
elif [[ $1 == 'on' ]]; then
    on
elif [[ $1 == 'sbr' ]]; then
    sbr $2
elif [[ $1 == 'dbr' ]]; then
    dbr
else
    echo "$0 off    -    for disable display"
    echo "$0 on    -    for enable mouse after disable display"
    echo "$0 sbr {value}   -    for set brightness"
    echo "$0 dbr    -    for disable brightness"
fi

