#
# ~/.bashrc
#

# If not running interactively, don't do anuthing
[[ $- != *i* ]] && return

PS1='[\u@\h \W]\$ '

# linux command aliases
alias ls='ls --color=auto'
alias ll="ls -lah"
alias grep='grep --color=auto'
alias cp="cp -v"
alias mv="mv -v"
alias rm="rm -v"

# alias for conda
# alias conda.update="conda update --all --yes"

# alias for create/activate python virtual envorenment
venv() {
    if test -e .venv; then
        source .venv/bin/activate
    else
        python -m venv .venv && source .venv/bin/activate
    fi
}

# ranger auto cd
rcd() {
    temp_file="$(mktemp -t "ranger_cd.XXXXXXXXXX")"
    ranger --choosedir="$temp_file" -- "${@:-$PWD}"
    if chosen_dir="$(cat -- "$temp_file")" && [ -n "$chosen_dir" ] && [ "$chosen_dir" != "$PWD" ]; then
        cd -- "$chosen_dir"
    fi
    rm -f -- "$temp_file"
}

# save current directory (it is necessary for tiling managers like i3, qtile)
export PROMPT_COMMAND="pwd > /tmp/whereami"

