" ----------------------------------------
" vimrc by Koljasha
" ----------------------------------------

" Базовые настройки
source ~/.vim/init/settings.vim

" Привязки клавиш
source ~/.vim/init/bindkeys.vim

" Терминал и Проводник
source ~/.vim/init/explorers.vim

" ----------------------------------------
" Плагины
" ----------------------------------------

" Vim-plug - менеджер плагинов
" ---------------
" https://github.com/junegunn/vim-plug
" Reload .vimrc and :PlugInstall to install plugins
" --------------

" Specify a directory for plugins
call plug#begin('~/.vim/plugged')

" ----------------------------------------

" Основные плагины
source ~/.vim/init/pluggins.vim

" IDE плагины общие
source ~/.vim/init/ide_main.vim

" IDE плагины Vim
if !has('nvim')
    source ~/.vim/init/ide_vim.vim
endif

" IDE плагины NeoVim
if has('nvim')
    source ~/.vim/init/ide_nvim.vim
endif

" ----------------------------------------

" Initialize plugin system
call plug#end()

" ----------------------------------------
" ----------------------------------------

" Цветовая схема (через плагин)
source ~/.vim/init/colors.vim

" ----------------------------------------
" ----------------------------------------

