" ----------------------------------------
" vimrc by Koljasha
" ----------------------------------------

" Базовые настройки
source ~/.vim/init/settings.vim

" Привязки клавиш
source ~/.vim/init/bindkeys.vim

" Терминал и Проводник
source ~/.vim/init/explorers.vim

" Плагины
source ~/.vim/init/pluggins.vim

" Цветовая схема (через плагин)
source ~/.vim/init/colors.vim

" ----------------------------------------
" ----------------------------------------

