#!/bin/bash

ln -sf /usr/share/zoneinfo/Europe/Moscow /etc/localtime
hwclock --systohc

sed -i 's/^#en_US.UTF-8/en_US.UTF-8/' /etc/locale.gen
sed -i 's/^#ru_RU.UTF-8/ru_RU.UTF-8/' /etc/locale.gen
locale-gen

echo "LANG=ru_RU.UTF-8" >> /etc/locale.conf
echo "KEYMAP=ru" >> /etc/vconsole.conf
echo "FONT=cyr-sun16" >> /etc/vconsole.conf

echo "archlinux" >> /etc/hostname

echo "127.0.0.1    localhost" >> /etc/hosts
echo "::1          localhost" >> /etc/hosts
echo "127.0.0.1    archlinux.localdomain  archlinux" >> /etc/hosts

systemctl enable NetworkManager

echo "####################"
echo "Password for root"
echo "####################"
passwd

echo "####################"
echo "Add user"
echo "####################"
read  -p"Username >" username
useradd -m -G wheel -s /bin/bash $username
passwd $username

sed -i 's/# %wheel ALL=(ALL) NO/%wheel ALL=(ALL) NO/' /etc/sudoers


echo "#### Install GRUB this ####"


echo "####################"
echo "Please do this:"
echo "exit"
echo "umount -R /mnt"
echo "reboot"
echo "####################"

